# Entries marked true will be tracked, false will not
ArrowsFired: true
BlocksBroke: true
BlocksBurned: true
BlocksPlaced: true
EggsThrown: true
ItemsCrafted: true
MobsKilled: true
PlayerDeaths: true
PlayersJoined: true
SnowballsThrown: true